package com.example.hci

import android.content.Intent
import android.os.Bundle
import android.support.design.widget.BottomNavigationView
import android.support.v4.app.FragmentTransaction
import android.support.v7.app.AppCompatActivity
import android.widget.TextView
import android.widget.Toast
import androidx.navigation.findNavController
import androidx.navigation.ui.AppBarConfiguration
import androidx.navigation.ui.setupWithNavController
import com.example.hci.ui.MyGroup.DashboardFragment
import com.example.hci.ui.MyProfile.NotificationsFragment
import com.example.hci.ui.home.HomeFragment

class MainActivity : AppCompatActivity() {

    companion object {
        var flagLogin = false
        var flagAlarm = false

        var uid :Int = -1
        var name : String = ""
        var score : Double = 0.0
        var location_id : Int = 1
        var email : String = ""


        var city :String = "서울특별시"
        var district :String = "광진구"
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val navView: BottomNavigationView = findViewById(R.id.nav_view)
        val navController = findNavController(R.id.nav_host_fragment)
        val appBarConfiguration = AppBarConfiguration(setOf(
                R.id.navigation_home, R.id.navigation_dashboard, R.id.navigation_notifications))
        navView.setupWithNavController(navController)
    }


    fun LocationIDSearch(number: Int): List<*> {
        val locations = listOf(
            listOf(1, "서울특별시", "종로구"),
            listOf(2, "서울특별시", "중구"),
            listOf(3, "서울특별시", "용산구"),
            listOf(4, "서울특별시", "성동구"),
            listOf(5, "서울특별시", "광진구"),
            listOf(6, "서울특별시", "동대문구"),
            listOf(7, "서울특별시", "중랑구"),
            listOf(8, "서울특별시", "성북구"),
            listOf(9, "서울특별시", "강북구"),
            listOf(10, "서울특별시", "도봉구"),
            listOf(11, "서울특별시", "노원구"),
            listOf(12, "서울특별시", "은평구"),
            listOf(13, "서울특별시", "서대문구"),
            listOf(14, "서울특별시", "마포구"),
            listOf(15, "서울특별시", "양천구"),
            listOf(16, "서울특별시", "강서구"),
            listOf(17, "서울특별시", "구로구"),
            listOf(18, "서울특별시", "금천구"),
            listOf(19, "서울특별시", "영등포구"),
            listOf(20, "서울특별시", "동작구"),
            listOf(21, "서울특별시", "관악구"),
            listOf(22, "서울특별시", "서초구"),
            listOf(23, "서울특별시", "강남구"),
            listOf(24, "서울특별시", "송파구"),
            listOf(25, "서울특별시", "강동구"),
            listOf(26, "경기도", "수원시"),
            listOf(27, "경기도", "성남시"),
            listOf(28, "경기도", "의정부시"),
            listOf(29, "경기도", "안양시"),
            listOf(30, "경기도", "부천시"),
            listOf(31, "경기도", "광명시"),
            listOf(32, "경기도", "동두천시"),
            listOf(33, "경기도", "평택시"),
            listOf(34, "경기도", "안산시"),
            listOf(35, "경기도", "고양시"),
            listOf(36, "경기도", "과천시"),
            listOf(37, "경기도", "구리시"),
            listOf(38, "경기도", "남양주시"),
            listOf(39, "경기도", "오산시"),
            listOf(40, "경기도", "시흥시"),
            listOf(41, "경기도", "군포시"),
            listOf(42, "경기도", "의왕시"),
            listOf(43, "경기도", "하남시"),
            listOf(44, "경기도", "용인시"),
            listOf(45, "경기도", "파주시"),
            listOf(46, "경기도", "이천시"),
            listOf(47, "경기도", "안성시"),
            listOf(48, "경기도", "김포시"),
            listOf(49, "경기도", "화성시"),
            listOf(50, "경기도", "광주시"),
            listOf(51, "경기도", "양주시"),
            listOf(52, "경기도", "포천시"),
            listOf(53, "경기도", "여주시"),
            listOf(54, "경기도", "연천군"),
            listOf(55, "경기도", "가평군"),
            listOf(56, "경기도", "양평군"),
            listOf(57, "인천광역시", "중구"),
            listOf(58, "인천광역시", "동구"),
            listOf(59, "인천광역시", "미추홀구"),
            listOf(60, "인천광역시", "연수구"),
            listOf(61, "인천광역시", "남동구"),
            listOf(62, "인천광역시", "부평구"),
            listOf(63, "인천광역시", "계양구"),
            listOf(64, "인천광역시", "서구"),
            listOf(65, "인천광역시", "강화군"),
            listOf(66, "인천광역시", "옹진군"),
            listOf(67, "대전광역시", "동구"),
            listOf(68, "대전광역시", "중구"),
            listOf(69, "대전광역시", "서구"),
            listOf(70, "대전광역시", "유성구"),
            listOf(71, "대전광역시", "대덕구"),
            listOf(72, "대구광역시", "중구"),
            listOf(73, "대구광역시", "동구"),
            listOf(74, "대구광역시", "서구"),
            listOf(75, "대구광역시", "남구"),
            listOf(76, "대구광역시", "북구"),
            listOf(77, "대구광역시", "수성구"),
            listOf(78, "대구광역시", "달서구"),
            listOf(79, "대구광역시", "달성군"),
            listOf(80, "대구광역시", "군위군"),
            listOf(81, "울산광역시", "중구"),
            listOf(82, "울산광역시", "남구"),
            listOf(83, "울산광역시", "동구"),
            listOf(84, "울산광역시", "북구"),
            listOf(85, "울산광역시", "울주군"),
            listOf(86, "전라남도", "목포시"),
            listOf(87, "전라남도", "여수시"),
            listOf(88, "전라남도", "순천시"),
            listOf(89, "전라남도", "나주시"),
            listOf(90, "전라남도", "광양시"),
            listOf(91, "전라남도", "담양군"),
            listOf(92, "전라남도", "곡성군"),
            listOf(93, "전라남도", "구례군"),
            listOf(94, "전라남도", "고흥군"),
            listOf(95, "전라남도", "보성군"),
            listOf(96, "전라남도", "화순군"),
            listOf(97, "전라남도", "장흥군"),
            listOf(98, "전라남도", "강진군"),
            listOf(99, "전라남도", "해남군"),
            listOf(100, "전라남도", "영암군"),
            listOf(101, "전라남도", "무안군"),
            listOf(102, "전라남도", "함평군"),
            listOf(103, "전라남도", "영광군"),
            listOf(104, "전라남도", "장성군"),
            listOf(105, "전라남도", "완도군"),
            listOf(106, "전라남도", "진도군"),
            listOf(107, "전라남도", "신안군"),
            listOf(108, "전라북도", "전주시"),
            listOf(109, "전라북도", "군산시"),
            listOf(110, "전라북도", "익산시"),
            listOf(111, "전라북도", "정읍시"),
            listOf(112, "전라북도", "남원시"),
            listOf(113, "전라북도", "김제시"),
            listOf(114, "전라북도", "완주군"),
            listOf(115, "전라북도", "진안군"),
            listOf(116, "전라북도", "무주군"),
            listOf(117, "전라북도", "장수군"),
            listOf(118, "전라북도", "임실군"),
            listOf(119, "전라북도", "순창군"),
            listOf(120, "전라북도", "고창군"),
            listOf(121, "전라북도", "부안군"),
            listOf(122, "충청남도", "청주시"),
            listOf(123, "충청남도", "천안시"),
            listOf(124, "충청남도", "공주시"),
            listOf(125, "충청남도", "보령시"),
            listOf(126, "충청남도", "아산시"),
            listOf(127, "충청남도", "서산시"),
            listOf(128, "충청남도", "논산시"),
            listOf(129, "충청남도", "계룡시"),
            listOf(130, "충청남도", "당진시"),
            listOf(131, "충청남도", "금산군"),
            listOf(132, "충청남도", "부여군"),
            listOf(133, "충청남도", "서천군"),
            listOf(134, "충청남도", "청양군"),
            listOf(135, "충청남도", "홍성군"),
            listOf(136, "충청남도", "예산군"),
            listOf(137, "충청남도", "태안군"),
            listOf(138, "충청북도", "청주시"),
            listOf(139, "충청북도", "충주시"),
            listOf(140, "충청북도", "제천시"),
            listOf(141, "충청북도", "보은군"),
            listOf(142, "충청북도", "옥천군"),
            listOf(143, "충청북도", "영동군"),
            listOf(144, "충청북도", "증평군"),
            listOf(145, "충청북도", "진천군"),
            listOf(146, "충청북도", "괴산군"),
            listOf(147, "충청북도", "음성군"),
            listOf(148, "충청북도", "단양군"),
            listOf(149, "세종특별자치시", "-"),
            listOf(150, "광주광역시", "동구"),
            listOf(151, "광주광역시", "서구"),
            listOf(152, "광주광역시", "남구"),
            listOf(153, "광주광역시", "북구"),
            listOf(154, "광주광역시", "광산구"),
            listOf(155, "부산광역시", "중구"),
            listOf(156, "부산광역시", "서구"),
            listOf(157, "부산광역시", "동구"),
            listOf(158, "부산광역시", "영도구"),
            listOf(159, "부산광역시", "부산진구"),
            listOf(160, "부산광역시", "동래구"),
            listOf(161, "부산광역시", "남구"),
            listOf(162, "부산광역시", "북구"),
            listOf(163, "부산광역시", "강서구"),
            listOf(164, "부산광역시", "해운대구"),
            listOf(165, "부산광역시", "사하구"),
            listOf(166, "부산광역시", "금정구"),
            listOf(167, "부산광역시", "연제구"),
            listOf(168, "부산광역시", "수영구"),
            listOf(169, "부산광역시", "사상구"),
            listOf(170, "부산광역시", "기장군"),
            listOf(171, "경상북도", "포항시"),
            listOf(172, "경상북도", "경주시"),
            listOf(173, "경상북도", "김천시"),
            listOf(174, "경상북도", "안동시"),
            listOf(175, "경상북도", "구미시"),
            listOf(176, "경상북도", "영주시"),
            listOf(177, "경상북도", "영천시"),
            listOf(178, "경상북도", "상주시"),
            listOf(179, "경상북도", "문경시"),
            listOf(180, "경상북도", "경산시"),
            listOf(181, "경상북도", "군위군"),
            listOf(182, "경상북도", "의성군"),
            listOf(183, "경상북도", "청송군"),
            listOf(184, "경상북도", "영양군"),
            listOf(185, "경상북도", "영덕군"),
            listOf(186, "경상북도", "청도군"),
            listOf(187, "경상북도", "고령군"),
            listOf(188, "경상북도", "성주군"),
            listOf(189, "경상북도", "칠곡군"),
            listOf(190, "경상북도", "예천군"),
            listOf(191, "경상북도", "봉화군"),
            listOf(192, "경상북도", "울진군"),
            listOf(193, "경상북도", "울릉군"),
            listOf(194, "경상남도", "창원시"),
            listOf(195, "경상남도", "진주시"),
            listOf(196, "경상남도", "통영시"),
            listOf(197, "경상남도", "사천시"),
            listOf(198, "경상남도", "김해시"),
            listOf(199, "경상남도", "밀양시"),
            listOf(200, "경상남도", "거제시"),
            listOf(201, "경상남도", "양산시"),
            listOf(202, "경상남도", "의령군"),
            listOf(203, "경상남도", "함안군"),
            listOf(204, "경상남도", "창녕군"),
            listOf(205, "경상남도", "고성군"),
            listOf(206, "경상남도", "남해군"),
            listOf(207, "경상남도", "하동군"),
            listOf(208, "경상남도", "산청군"),
            listOf(209, "경상남도", "함양군"),
            listOf(210, "경상남도", "거창군"),
            listOf(211, "경상남도", "합천군"),
            listOf(212, "강원도", "춘천시"),
            listOf(213, "강원도", "원주시"),
            listOf(214, "강원도", "강릉시"),
            listOf(215, "강원도", "동해시"),
            listOf(216, "강원도", "태백시"),
            listOf(217, "강원도", "속초시"),
            listOf(218, "강원도", "삼척시"),
            listOf(219, "강원도", "홍천군"),
            listOf(220, "강원도", "횡성군"),
            listOf(221, "강원도", "영월군"),
            listOf(222, "강원도", "평창군"),
            listOf(223, "강원도", "정선군"),
            listOf(224, "강원도", "철원군"),
            listOf(225, "강원도", "화천군"),
            listOf(226, "강원도", "양구군"),
            listOf(227, "강원도", "인제군"),
            listOf(228, "강원도", "고성군"),
            listOf(229, "강원도", "양양군")
        )
        val selectedLocation = locations.find { it[0] == number }
        return selectedLocation.let { listOf(it?.get(1), it?.get(2)) }
    }
}